### PR TITLE
Ignore gradient of generate_cluster

### PR DESCRIPTION
**Pull request by yuehhua**
Inspired by #55

### CODE REVIEW

**Comment by ilancoulon** [comment]
Unfortunately, Zygote.ignore() seems to be only available with Zygote version >= 0.5.
But [Flux is not yet compatible](https://github.com/FluxML/Flux.jl/pull/1241) with v0.5...

**Comment by yuehhua** [comment]
Fine. We can do it in another way.

**Comment by ilancoulon** [comment]
Great! Thank you very much!

I think it will soon be possible to switch to `ignore`, they're actively working on it.

**Comment by ilancoulon** [comment]
Oh, that's what I thought, adding it to #55 does not let the tests pass. I had actually tried that and it gives that error: `Can't differentiate foreigncall expression`.
I really don't know much about Zygote... Do you know how this could be solved?

**Comment by yuehhua** [comment]
Could you please paste the full error message here? Thanks.

**Comment by ilancoulon** [comment]
You can reproduce it by launching the tests of #55, or by lauching the code in #54 using the version of #55.
Here it is:
```
ERROR: LoadError: Can't differentiate foreigncall expression
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\threadingconstructs.jl:69 [inlined]
 [3] #_apply_msg!#106 at C:\[...]\GeometricFlux.jl\src\layers\msgpass.jl:23 [inlined]
 [4] (::typeof(∂(#_apply_msg!#106)))(::Array{Float64,2}) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface2.jl:0 (repeats 2 times)
 [5] #update_edge#105 at C:\[...]\GeometricFlux.jl\src\layers\msgpass.jl:19 [inlined]
 [6] (::typeof(∂(#update_edge#105)))(::Array{Float64,2}) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface2.jl:0 (repeats 2 times)
 [7] #propagate#111 at C:\[...]\GeometricFlux.jl\src\layers\msgpass.jl:46 [inlined]
 [8] (::typeof(∂(#propagate#111)))(::FillArrays.Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface2.jl:0 (repeats 2 times)
 [9] GATConv at C:\[...]\GeometricFlux.jl\src\layers\conv.jl:283 [inlined]
 [10] (::typeof(∂(λ)))(::FillArrays.Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface2.jl:0
 [11] #5 at C:\[...]\failgat.jl:12 [inlined]
 [12] (::typeof(∂(#5)))(::Float64) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface2.jl:0
 [13] (::Zygote.var"#49#50"{Zygote.Params,Zygote.Context,typeof(∂(#5))})(::Float64) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface.jl:179
 [14] gradient(::Function, ::Zygote.Params) at C:\[...]\.juliapro\JuliaPro_v1.4.2-1\packages\Zygote\YeCEW\src\compiler\interface.jl:55
 [15] top-level scope at C:\[...]\failgat.jl:12
 [16] include(::Module, ::String) at .\Base.jl:377
 [17] exec_options(::Base.JLOptions) at .\client.jl:288
 [18] _start() at .\client.jl:484
in expression starting at C:\[...]\failgat.jl:12
```

**Comment by yuehhua** [comment]
Oh! Threading!
Thread is not differentiable, so I have to define @adjoint on `_apply_msg!`.

**Pull request merged**
